version: '3.9'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - ./db_dumps:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    ports:
      - ${DB_CONTAINER_HOST_PORT}:3306
    networks:
      containers-network:

  www:
    depends_on:
      - db
    build:
      context: .
      dockerfile: www.Dockerfile
    container_name: ${SERVER_CONTAINER_NAME}
    volumes:
      - "./app:${SERVER_DEVMENT_DIR}/app"
      - "./composer.json:${SERVER_DEVMENT_DIR}/composer.json"
    ports:
      - ${SERVER_HTTP_HOST_PORT}:80
      - ${SERVER_HTTPS_HOST_PORT}:443
    networks:
      containers-network:

volumes:
  db-data:
    name: ${DB_CONTAINER_VOLUME_NAME}
    external: ${DB_CONTAINER_VOLUME_EXTERNAL}

networks:
  containers-network:
    driver: bridge